# Generated by Django 6.0.6 on 2026-06-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='event_image',
            field=models.ImageField(null=True, upload_to='media/photos'),
        ),
    ]
