# Generated by Django 6.0.6 on 2026-06-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0002_eventmodel_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='event_status',
            field=models.CharField(choices=[('Not_Started', 'Not_Started'), ('In_Progress', 'In_Progress'), ('Completed', 'Completed')], max_length=50, null=True),
        ),
    ]
