# Generated by Django 6.0.6 on 2026-06-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0003_alter_eventmodel_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='event_status',
            field=models.CharField(choices=[('Not_Started', 'Not Started'), ('In_Progress', 'In Progress'), ('Completed', 'Completed')], max_length=50, null=True),
        ),
    ]
